WebPortal/Controllers/Shared/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Identity;
using WebPortal.Security;
using Microsoft.AspNetCore.Authorization;

namespace WebPortal.Controllers.Shared
{
    public class UsersController : Controller
    {
        private UserManager<AppUser> AppUserManager;
        private SignInManager<AppUser> AppSignInManager;

        public UsersController(UserManager<AppUser> _userManager, SignInManager<AppUser> _signinManager)
        {
            AppUserManager = _userManager;
            AppSignInManager = _signinManager;
        }
            
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginViewModel model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            if (ModelState.IsValid)
            {
                // This doesn't count login failures towards account lockout
                // To enable password failures to trigger account lockout, set lockoutOnFailure: true
                var result = await AppSignInManager.PasswordSignInAsync(model.LoginId,
                    model.Password, model.RememberMe, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                   // _logger.LogInformation(1, "User logged in.");
                    return RedirectToAction("/provider/index");
                }
                //if (result.RequiresTwoFactor)
                //{
                //    return RedirectToAction(nameof(SendCode), new { ReturnUrl = returnUrl, RememberMe = model.RememberMe });
                //}
                //if (result.IsLockedOut)
                //{
                //    _logger.LogWarning(2, "User account locked out.");
                //    return View("Lockout");
                //}
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                    return View(model);
                }
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Signup(RegisterViewModel model)
        {
            
            if (ModelState.IsValid)
            {
                var user = new AppUser { Email = model.LoginId, UserName = model.LoginId, FirstName=model.FirstName,LastName=model.LastName };
                var result = await AppUserManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("~/provider/index", "Home");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
            }

            return View(model);
        }
    }

    public class RegisterViewModel
    {
        [Required]
        public String LoginId { get; set; }
        [Required]
        public String FirstName { get; set; }
        [Required]
        public String LastName { get; set; }
        [Required, DataType(DataType.Password)]
        public String Password { get; set; }
        [DataType(DataType.Password), Compare(nameof(Password))]
        public String ConfirmPassword { get; set; }
    }

    public class LoginViewModel
    {   
        [Required]
        public String LoginId { get; set; }
        [Required]
        public String Password { get; set; }

        [Required]
        public Boolean RememberMe { get; set; }

    }
}

WebPortal/Views/Users/Login.cshtml
@model WebPortal.Controllers.Shared.LoginViewModel
    ViewData["Title"] = "Login";
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}

<style>
    .cust-login-panel{
        width:400px;
    }
    .form-horizontal .row{
        margin-bottom:2px;
    }
    .cust-login-panel .btn-primary {
        width:100px;
    }

</style>

<h2>Clients Login</h2>
<form asp-controller="Users" asp-action="Login" method="post">

<div class="container form-horizontal cust-login-panel">
    <div class="row">
        <span class="control-label">Login Id</span>
        <input type="text" asp-for="LoginId" class="form-control" />
    </div>

    <div class="row">
        <span class="control-label">Password</span>
        <input type="password" asp-for="Password" class="form-control" />
    </div>

    <div class="row">
        <input type="checkbox" asp-for="RememberMe" class="checkbox" />
        <span>Remember Me</span>
    </div>
    <div class="row">
            <div class="form-inline">
                <input type="button" class="form-control btn-primary inline"  value="Login" />
                <span ><a href="">Forgot Password?</a></span>
            </div>
                
                
        </div>
    <br />
    <div class="row">
        <h5><a href="">Not Registered? Sign up New Account </a></h5>
    </div>

</div>

    </form>

WebPortal/Views/Users/Signup.cshtml
@model WebPortal.Controllers.Shared.RegisterViewModel
@{
    ViewData["Title"] = "Signup";
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}


<style>
    .cust-login-panel {
        width: 400px;
    }

    .form-horizontal .row {
        margin-bottom: 2px;
    }

    .cust-login-panel .btn-primary {
        width: 100px;
    }

    
</style>
<h2>Sign Up</h2>
<form asp-controller="Users" asp-action="Signup" method="post">
    <div asp-validation-summary="ModelOnly"></div> 
    <div class="container form-horizontal cust-login-panel">
        <div class="row">
            <div class="col-md-12">
                <span class="control-label">Email</span>
                <input type="text" asp-for="LoginId" class="form-control" />
                <span asp-validation-for="LoginId"></span>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <span class="control-label">First Name</span>
                <input type="text" asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName"></span>
            </div>
            <div class="col-md-6">
                <span class="control-label">Last Name</span>
                <input type="text" asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName"></span>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <span class="control-label">Password</span>
                <input type="password" asp-for="Password" class="form-control" />
                <span asp-validation-for="Password"></span>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <span class="control-label">Confirm Password</span>
                <input type="password" asp-for="ConfirmPassword" class="form-control" />
                <span asp-validation-for="ConfirmPassword"></span>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <input type="submit" class="form-control btn-primary" value="Submit" />
            </div>
        </div>

        <div class="row">
            <span>@ViewData["error"]</span>
        </div>

    </div>

</form>