WebPortal/Models/Hotels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebPortal.Models
{
    public class Hotel 
    {

        public long Id { get; set; }
        public String Name { get; set; }
    }
}

WebPortal/Controllers/Services/HotelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WebPortal.Controllers.Services
{
    public class HotelController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        
        public IActionResult SetUp()
        {
            return View();
        }

        public IActionResult BasicInfo()
        {
            return View();
        }
    }
}

WebPortal/Views/Hotel/BasicInfo.cshtml
@{
    ViewData["Title"] = "BasicInfo";
    Layout = "~/Views/Hotel/SetUp.cshtml";
}

<style>
        .cust-child-container {
            padding-left:50px;
        }

        .cust-child-container .row {
            margin-bottom:2px;
        }

        .col-md-4 {
            padding-left:0px;
        }
        .cust-map-placeholder {
            width:58%;
            height:100px;
            background-color:lightgray;
            padding-top:50px;
        }

    .cust-btn-submit {
        width: 58%;
    }
</style>


<h2>BasicInfo</h2>
<div class="container cust-child-container">
    <form method="post" asp-controller="Hotel" asp-action="AddBasicInfo">

        <div class="row">
            <label class="control-label">Property Name</label>
            <input type="text" class="form-control" />
        </div>
        <div class="row">
            <div class="col-md-4">
                <label class="control-label">Payment Type</label>
                <select class="form-control"></select>
            </div>
            <div class="col-md-6">
                <label class="control-label">Star Rating</label>
                <select class="form-control"></select>
            </div>
        </div>

        <div class="row">
            <label class="control-label">No. Of Rooms</label>
            <input type="text" class="form-control" />
        </div>

        <div class="row">
            <h2>Address</h2>
        </div>
        <div class="row">
            <label class="control-label">Property Name</label>
            <input type="text" class="form-control" />
        </div>
        <div class="row">
            <label class="control-label">Property Name</label>
            <input type="text" class="form-control" />
        </div>

        <div class="row">
            <label class="control-label">Payment Type</label>
            <select class="form-control"></select>
        </div>
        <div class="row">
            <div class="col-md-4">
                <label class="control-label">Star Rating</label>
                <input type="text" class="form-control" />
            </div>
            <div class="col-md-4">
                <label class="control-label">Payment Type</label>
                <input type="text" class="form-control" />
            </div>
        </div>

        <div class="row">
            <div class="cust-map-placeholder text-center">MAP</div>
        </div>

        <div class="row table-bordered">
                <input type="button" class="btn" value="Continue " style="width:50px;" />
        </div>
        </form>
</div>

WebPortal/Views/Hotel/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_HotelLayout.cshtml";
}

<h2>Index</h2>

WebPortal/Views/Hotel/SetUp.cshtml
@{
    ViewData["Title"] = "SetUp";
    Layout = "~/Views/Shared/_HotelLayout.cshtml";
}

<style>
    .sidebar-nav .navbar .navbar-collapse {
        padding: 0;
        max-height: none;
        color: #fff;
    }

    .sidebar-nav .navbar ul {
        float: none;
        display: block;
        color: #fff;
    }

    .sidebar-nav .navbar li {
        float: none;
        display: block;
    }

        .sidebar-nav .navbar li a {
            padding-top: 12px;
            padding-bottom: 12px;
            color: #fff;
            text-align:center;
        }
        .sidebar-nav .navbar li a:hover {
            color: #fff;
        }
        .sidebar-nav .navbar-nav {
            background-color:#000;
        }

    .sidebar-nav .navbar-nav > .active > a,
    .sidebar-nav .navbar-nav > .active > a:hover,
    .sidebar-nav .navbar-nav > .active > a:focus {
        color: #fff;
        background-color: #ff6a00;
    }

    .cust-main-container {
        min-height: 450px;
        width: 100%;
        padding-left: 0px;
    }

    .col-sm-3 {
        height: 100%;
    }

    .cust-side-bar {
        height: 100%;
   
        background-color: #000;
    }

</style>


<div class="container cust-main-container">
        <div class="row">
        <div class="col-sm-3">
            <div class="sidebar-nav">
                <div class="navbar navbar-default" role="navigation">
                    <div class="navbar-collapse collapse sidebar-navbar-collapse cust-side-bar">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="@Url.Action("BasicInfo","Hotel")">Basic Info</a></li>
                            <li><a href="@Url.Action("BasicInfo","Hotel")">Property Details</a></li>
                            <li><a href="@Url.Action("PropertyDetails","Hotel")">Property Details</a></li>
                            <li><a href="@Url.Action("RoomDetails","Hotel")">Room Details</a></li>
                            <li><a href="@Url.Action("RoomAmenities","Hotel")">Room Amenities</a></li>
                            <li><a href="@Url.Action("Photos","Hotel")">Photos</a></li>
                            <li><a href="@Url.Action("Payment","Hotel")">Payment & Policies</a></li>
                            <li><a href="@Url.Action("Agreement","Hotel")">Agreement</a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>

        <div class="col-sm-9">
            @RenderBody()
        </div>
    </div>
</div>